default: &default
  admin:
    name:
    password:

  blockchains:
    bip32:
      master_extended_private_key: xprvA2JUKN9GQhLhFcLciYtaG8cMnyVkYgd6qUDsnkaRgu83CFALsU58zQj48zKGnxRiCyWqhvcq6KKndPETD5ZVj6oaZdcLAZrMM8i6D529bsK
      master_extended_public_key: xpub6FHpisgAF4tzU6R5paRadGZ6M1LEx9LxCh9Ub8z3FEf253VVR1PPYD3XzHmJ6dxUzG37XjyeeZBsZoTr4bKtcF9ZvmMuNWbfraqa5FfUr1i
      master_mnemonic: adjust wire before rail wonder angle caution series flame shaft few prefer pyramid barrel bomb
    bitcoin:
      master_address:
    ethereum:
      endpoint:
      master_address:

  markets:
    binance:
      addresses:
        inbound:
      api_key_id:
      api_key:
      secret_key:

  secret_key_base: 8068d679073f4f9dc2e12326007f1a295c069e0c2f491066a081898c5d45ca12bfbd1c950f21e5bdc145f8af557d82ddd19d57b298bf210de2828d51eed6b032
  secret_keys:
    asymmetric:
      private_key: 'replaceme'
      public_key: 'replaceme'
    symmetric: c+yOxn4C78SZQRtf8J8wCfwQYTZDkRLTzZfkgyw+EwaV

  services:
    freshchat:
      token:
    google:
      maps_api_key:
    twilio:
      account_sid:
      auth_token:
      sender_phone:

development:
  <<: *default

test:
  <<: *default
